export const columnNames = {
	firstname: "Prénom",
	lastname: "Nom",
	email: "Email",
	name: "Nom",
	description: "Description",
	gender: "Genre",
	createdAt: "Date de création",
	role: "Rôle",
	disabled: "Statut",
	id: "ID",
	passwordUpdatedAt: "Date de modification du mot de passe",
	passwordResetToken: "Token de réinitialisation du mot de passe",
	birthdate: "Date de naissance",
	address: "Adresse",
	postalCode: "Code postal",
	city: "Ville",
	phone: "Téléphone",
	loginAttempts: "Nombre de tentatives de connexion",
	blockedAt: "Date de blocage",
	isValidate: "E-mail confirmé",
	authentificationToken: "Token d'authentification",
	updatedAt: "Date de modification",
	price: "Prix",
	vat: "TVA",
	quantity: "Qté",
	size: "Taille",
	color: "Couleur",
	status: "Statut",
	userId: "ID utilisateur",
	deliveryAddress: "Adresse de livraison",
	products: "Produits",
	user: "ID utilisateur",
	sku: "SKU",
	discount: "Réduction",
	alertQuantity: "Qté. avant alerte",
	deletedAt: "Date de suppression",
	modelId: "ID modèle",
	productImage: "Image",
	productImages: "Images",
	model: "Modèle",
	models: "Modèles",
};
