name: Unit Tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: [ master, dev ]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          cd api
          npm install
          npm test